# Generated by Django 5.0.6 on 2026-08-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('booking_requested', 'Booking Requested'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('booking_completed', 'Booking Completed'), ('payment_received', 'Payment Received'), ('new_message', 'New Message'), ('new_review', 'New Review'), ('event_reminder', 'Event Reminder')], max_length=30),
        ),
    ]
