# Generated by Django 5.0.6 on 2026-08-11 06:31

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_referral_code_user_referred_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=apps.users.models.generate_referral_code, editable=False, max_length=20, unique=True),
        ),
    ]
