# Generated by Django 5.0.6 on 2026-08-11 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcollaborator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday Party'), ('surprise_birthday', 'Surprise Birthday'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('proposal', 'Proposal'), ('housewarming', 'Housewarming'), ('graduation', 'Graduation Party'), ('farewell', 'Farewell Party'), ('family_gathering', 'Family Gathering'), ('corporate_party', 'Corporate Party'), ('product_launch', 'Product Launch'), ('team_celebration', 'Team Celebration'), ('office_anniversary', 'Office Anniversary'), ('employee_appreciation', 'Employee Appreciation'), ('networking', 'Networking Event'), ('custom', 'Custom Celebration')], max_length=30)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('budget_categories', models.JSONField(blank=True, default=list, help_text='List of {"category": "...", "planned_amount": "..."} objects.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
