# Generated by Django 5.0.6 on 2026-08-06 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('decoration', 'Decoration Company'), ('balloon_decor', 'Balloon Decoration'), ('photography', 'Photography'), ('videography', 'Videography'), ('dj', 'DJ'), ('live_music', 'Live Music'), ('catering', 'Catering'), ('cake_shop', 'Cake Shop'), ('magician', 'Magician'), ('anchor', 'Anchor'), ('lighting', 'Lighting'), ('stage_decor', 'Stage Decoration'), ('entertainment', 'Entertainment Company')], max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('cover_image_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='planners.plannerprofile')),
            ],
        ),
    ]
