# Generated by Django 5.0.6 on 2026-08-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0005_portfoliophoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
