# Generated by Django 5.0.6 on 2026-08-06 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday Party'), ('surprise_birthday', 'Surprise Birthday'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('proposal', 'Proposal'), ('housewarming', 'Housewarming'), ('graduation', 'Graduation Party'), ('farewell', 'Farewell Party'), ('family_gathering', 'Family Gathering'), ('corporate_party', 'Corporate Party'), ('product_launch', 'Product Launch'), ('team_celebration', 'Team Celebration'), ('office_anniversary', 'Office Anniversary'), ('employee_appreciation', 'Employee Appreciation'), ('networking', 'Networking Event'), ('custom', 'Custom Celebration')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
